// <auto-generated />
using System;
using DataAcquisitionSystemModbusProtocol.DataAccess.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAcquisitionSystemModbusProtocol.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.27");

            modelBuilder.Entity("Domain.Entities.Samples.Sample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SampleDateTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VariableId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VariableId");

                    b.ToTable("Samples", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Units.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Units", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Variables.Variable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModbusProtocolDirection")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SamplingPeriod")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("TEXT");

                    b.Property<int>("VariableType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("Variables", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Variables.AnalogicVariable", b =>
                {
                    b.HasBaseType("Domain.Entities.Variables.Variable");

                    b.ToTable("AnalogicVaruables", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Variables.DigitalVariable", b =>
                {
                    b.HasBaseType("Domain.Entities.Variables.Variable");

                    b.ToTable("DigitalVariables", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Samples.Sample", b =>
                {
                    b.HasOne("Domain.Entities.Variables.Variable", "Variable")
                        .WithMany("Samples")
                        .HasForeignKey("VariableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Variable");
                });

            modelBuilder.Entity("Domain.Entities.Variables.Variable", b =>
                {
                    b.HasOne("Domain.Entities.Units.Unit", "Unit")
                        .WithMany("Variables")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Domain.Entities.Variables.AnalogicVariable", b =>
                {
                    b.HasOne("Domain.Entities.Variables.Variable", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Variables.AnalogicVariable", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Variables.DigitalVariable", b =>
                {
                    b.HasOne("Domain.Entities.Variables.Variable", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Variables.DigitalVariable", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Units.Unit", b =>
                {
                    b.Navigation("Variables");
                });

            modelBuilder.Entity("Domain.Entities.Variables.Variable", b =>
                {
                    b.Navigation("Samples");
                });
#pragma warning restore 612, 618
        }
    }
}
